# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
# command_timeout = 1000

# Change the default prompt format
format = """[â•­â•´](bold dimmed green)$env_var[âŒª](bold dimmed green)$username$hostname[âŒª](bold dimmed green)$memory_usage[âŒª](bold dimmed green)$battery
[â”‚](bold dimmed green)$time$shlvl$singularity$kubernetes$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$docker_context$package$cmake$cobol$dart$deno$dotnet$elixir$elm$erlang$golang$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$nix_shell$conda$aws$gcloud$openstack$azure$crystal$custom$sudo$cmd_duration$jobs$status$shell$directory
[â•°â”€](bold dimmed green)$character"""

# Change the default prompt characters
[character]
error_symbol = "[â€¼ï¸](bold red) "
success_symbol = "[â¯](bold green) "

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
disabled = false
format = ' [$env_value](bold white)[âŒª](bold dimmed green)'
variable = "STARSHIP_DISTRO"

[env_var.IP]
disabled = false
format = "ğŸŒ[$env_value](bold white)"
variable = "IP"

# Shows the username
[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bold red"
style_user = "bold yellow"

[hostname]
disabled = false
format = "[@$hostname](bold yellow)"
ssh_only = false

[directory]
format = " at [$path]($style)[$read_only]($read_only_style)"
home_symbol = "ğŸ  ~"
read_only = " ğŸ”’ "
read_only_style = "197"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
format = " on [$symbol$branch]($style)"
style = "bold green"
symbol = "ğŸŒ±"
truncation_length = 30
truncation_symbol = "â€¦/"

[git_status]
conflicted = "ğŸš©"
up_to_date = "âœ…"
untracked = "â“"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++($count)](green)'
renamed = "ğŸ”§"
deleted = "ğŸ—‘ï¸"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
format = '([\[$all_status$ahead_behind\]]($style))'

[git_state]
format = '[($state( $progress_current of $progress_total))]($style)'
cherry_pick = " [ğŸ’ PICKING](bold red)"

[docker_context]
format = " [ïŒˆ$context](bold blue)"

[helm]
format = " [ïˆš$version](bold purple)"

[python]
python_binary = "python3"
symbol = " ï Ÿ"

[nodejs]
disabled = false
format = " [ï¢˜$version](bold green)"

[time]
disabled = false
format = "ğŸ•™[$time](yellow)"
time_format = "%T"
utc_time_offset = "-3"

[cmd_duration]
format = ' [\(â³$duration\)](bold yellow)'
min_time = 1000

[battery]
format = "[$symbol$percentage]($style)"
disabled = false

[[battery.display]]  
threshold = 20
style = "bold red"

[[battery.display]] 
threshold = 40
style = "bold yellow"

[[battery.display]]  
threshold = 100
style = "bold white"

[lua]
format = " [ğŸŒ•$version](bold blue)"

[memory_usage]
disabled = false
format = "[ğŸ$ram_pct â™»ï¸$swap_pct](bold green)"
threshold = -1
symbol = " "

[package]
format = " [ğŸ“¦$version](bold)"

[java]
format = " â˜•"

[dotnet]
format = " [î¿](bold cyan)"
style = "green"
heuristic = false

[sudo]
style = "bold green"
symbol = "ğŸ§™"
allow_windows = true
disabled = false